In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import numpy as np

In [4]:
digits = load_digits()

In [7]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [8]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [9]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [ ]:
#training the data model

In [5]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
#our dataframe divided in 3 splits i.e n_splits=3

In [26]:
folds = StratifiedKFold(n_splits=3)

In [27]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [ ]:
#lists for storing the score for Logistic Regression, SVM and Random Forest

In [34]:
scores_lr = []
scores_svm = []
scores_rf = []


In [35]:
for train_index, test_index in folds.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

C:\Users\ABHI\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ABHI\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

In [49]:
scores_lr = np.array(scores_lr)
print(scores_lr)
scores_lr.mean()


[0.92153589 0.94156928 0.91652755]


0.9265442404006677

In [50]:
scores_svm = np.array(scores_svm)
print(scores_svm)
scores_svm.mean()

[0.96494157 0.97996661 0.96494157]


0.9699499165275459

In [51]:
scores_rf = np.array(scores_rf)
print(scores_rf)
scores_rf.mean()

[0.93823038 0.96327212 0.92654424]


0.9426822481914301

In [ ]:
#instead of for loop we use to calculate the score, we can use cross_val_score

In [52]:
from sklearn.model_selection import cross_val_score

In [64]:
print(cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3))
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3).mean()

C:\Users\ABHI\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ABHI\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

[0.92153589 0.94156928 0.91652755]


C:\Users\ABHI\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ABHI\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

0.9265442404006677

In [62]:
print(cross_val_score(SVC(),digits.data,digits.target,cv=3))
cross_val_score(SVC(),digits.data,digits.target,cv=3).mean()

[0.96494157 0.97996661 0.96494157]


0.9699499165275459

In [63]:
print(cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3))
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3).mean()

[0.93656093 0.95826377 0.93989983]


0.9415692821368947